/*
 * This source file was generated by the Gradle 'init' task
 */
package tradingportfolio;

import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        try {
            CSVReader csvReader = new CSVReader();
            List<Position> positions = csvReader.readPositions("src/main/resources/positions.csv");

            DatabaseSetup dbSetup = new DatabaseSetup();
            dbSetup.connect();
            dbSetup.setupSchema();

            Map<String, Stock> stocks = dbSetup.loadStocks();

            PortfolioValuation valuation = new PortfolioValuation(stocks, positions);
            MarketDataProvider marketDataProvider = new MarketDataProvider(stocks, valuation);
            Thread marketDataThread = new Thread(marketDataProvider);
            marketDataThread.start();


        } catch (IOException e){
            System.err.println("Error reading positions from CSV: " + e.getMessage());
            e.printStackTrace();

        } catch (SQLException e){
            System.err.println("Database error: " + e.getMessage());
            e.printStackTrace();

        } catch (Exception e){
            System.err.println("An unexpected error occured: " + e.getMessage());
            e.printStackTrace();
        }
        
        
    
        
    
    }
}
